rootProject.name = "spring-tips-examples"

include("rsocket")
include("rsocket-spring-boot:consumer")
include("rsocket-spring-boot:producer")
include("rsocket-spring-security:service")
include("rsocket-spring-security:client")
include("intro-to-spring-integration")
include("spring-integration-kotlin-dsl")
include("programmatic-bean-registration")
include("spring-aware-beans")
include("spring-batch")
include("server-sent-events:spring-mvc")
include("server-sent-events:spring-webflux")
include("spring-webflux-reactive-client")
include("reactive-web-views")
include("spring-cloud-stream:producer")
include("spring-cloud-stream:consumer")
include("spring-cloud-stream-kafka")
include("webmvc-fn")
include("webflux-fn")
include("spring-apache-camel")
include("jdbc")
include("jpa")
include("spring-boot-plugin")
include("bootiful-testing")
include("circuit-breakers:robust-client")
include("circuit-breakers:hystrix-dashboard")
