server:
  port: 9999

spring:
  application:
    name: gateway
  config:
    import: configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: false
