spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useSSL=false
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
