spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/bootstrap/
server:
  port: 8888
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
